[[LCIO_Julia_Wrapper]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e929b12ffcfa644b57fd752ba886dc09f17838f0"
os = "macos"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "493b35cb9a203f1e32b9d6b198d4293a8dbd652a148276f1103fb10ffdb5a532"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.9.0+1/LCIO_Julia_Wrapper.v0.9.0.x86_64-apple-darwin14-cxx11.tar.gz"
[[LCIO_Julia_Wrapper]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b3ec568b32c7dccdef54c15bab8f39968d834df8"
libc = "glibc"
os = "linux"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "dbb8a866297fadcd1ce0fc2d5b11a4d3243fdbc701c8ce489235c7ab5f3ebd3c"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.9.0+1/LCIO_Julia_Wrapper.v0.9.0.x86_64-linux-gnu-cxx11.tar.gz"
