[[LCIO_Julia_Wrapper]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3b618d3c10a824474ca0226f50ec7541553a7940"
os = "macos"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "44733aac2ef87336f98edd3e9a5102549b698592022698a1ab97bf9b90681454"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.12.0+0/LCIO_Julia_Wrapper.v0.12.0.x86_64-apple-darwin14-cxx11.tar.gz"
[[LCIO_Julia_Wrapper]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f2ea63774729aeec74eac8f371284ff0fef91e78"
libc = "glibc"
os = "linux"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "b1a9252301dac9894b71832e6ac4d4eb04afb38f48859966eaadf50eb1957cc6"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.12.0+0/LCIO_Julia_Wrapper.v0.12.0.x86_64-linux-gnu-cxx11.tar.gz"
