[[LCIO_Julia_Wrapper]]
arch = "x86_64"
git-tree-sha1 = "1465d3abdc0ed6806d49ca150bcd4342349287d5"
os = "macos"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "e782f1e69c154c4cc4d0df88d146772396a2542d2e2fee74ed8100b0414bbf46"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.8.2+0/LCIO_Julia_Wrapper.v0.8.2.x86_64-apple-darwin14.tar.gz"
[[LCIO_Julia_Wrapper]]
arch = "x86_64"
git-tree-sha1 = "d131455dfbf08a53d3c898a250e2aace6a0f398d"
libc = "glibc"
os = "linux"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "002ff7c9a93a05509ab79ba4ce867631a01acd5080fb2333a71b3698d9def244"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.8.2+0/LCIO_Julia_Wrapper.v0.8.2.x86_64-linux-gnu.tar.gz"
