[[LCIO_Julia_Wrapper]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c1d732ce9529007a3236a6a602087331ff2bf778"
os = "macos"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "1566887c100acf6e5ec90103f3ff974e40753e5174e0de79762bff633a760985"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.12.1+0/LCIO_Julia_Wrapper.v0.12.1.x86_64-apple-darwin14-cxx11.tar.gz"
[[LCIO_Julia_Wrapper]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4d4f57ad94dc17bee0deee5a57d9d335386fda18"
libc = "glibc"
os = "linux"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "900277f9087e08fea1db27a664a6ef8a81d5b05438c94f288c2d35908c0641d5"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.12.1+0/LCIO_Julia_Wrapper.v0.12.1.x86_64-linux-gnu-cxx11.tar.gz"
