[[LCIO_Julia_Wrapper]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "83e005e038ca1276dc470b556cb7ff5040b1cf36"
os = "macos"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "4cb10bc740ec519599a97bfdde97d4a480a950cea6e3d7d1796da48d5e2a135b"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.8.0+0/LCIO_Julia_Wrapper.v0.8.0.x86_64-apple-darwin14-cxx11.tar.gz"
[[LCIO_Julia_Wrapper]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "df10c28d6e4acec9d0a59123e6d09abc6d60ce8f"
os = "macos"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "6180cc9fd1e957815a2be8e2f9e5b0847710904fcaf49f8d57ef6db1a2141b2c"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.8.0+0/LCIO_Julia_Wrapper.v0.8.0.x86_64-apple-darwin14-cxx03.tar.gz"
[[LCIO_Julia_Wrapper]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d35199c35ebe1e7e890afc026cb15364f9eae648"
libc = "glibc"
os = "linux"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "345b418768b348303bbad243d735adc02cef6e0ac985830300caee9b6b28da59"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.8.0+0/LCIO_Julia_Wrapper.v0.8.0.x86_64-linux-gnu-cxx11.tar.gz"
[[LCIO_Julia_Wrapper]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e3ad1886490e1d88f7aefcc1c3c2c89f8f53ad4e"
libc = "glibc"
os = "linux"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "bd12d9a027cd9efb5301f2643cf9eaa7751c3e6bff46a50b4c9d0adb77fc1d16"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.8.0+0/LCIO_Julia_Wrapper.v0.8.0.x86_64-linux-gnu-cxx03.tar.gz"
