[[LCIO_Julia_Wrapper]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b6eda66fe80983dec2105f4c0e0938834b019fd3"
os = "macos"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "254cb0c8a037be5dc7e041b5e56f42c534a40d08ee85dc1fcf4b5ceb004bfd0f"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.12.2+0/LCIO_Julia_Wrapper.v0.12.2.x86_64-apple-darwin-cxx11.tar.gz"
[[LCIO_Julia_Wrapper]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a616d6a55c97eee581d634500da56ceb5fa257b9"
libc = "glibc"
os = "linux"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "c4d36ec531686ce5ef84e3025bdc7767b611205a75a44be67d972055252c0702"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.12.2+0/LCIO_Julia_Wrapper.v0.12.2.x86_64-linux-gnu-cxx11.tar.gz"
