[[LCIO_Julia_Wrapper]]
arch = "x86_64"
git-tree-sha1 = "44d5f7881aa472efd10c941a932b2617bc66ed76"
os = "macos"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "f150e3ddec8486a37c941d25df865de9d07d8e90fba7e658aec0b2d912bf71e4"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.13.1+1/LCIO_Julia_Wrapper.v0.13.1.x86_64-apple-darwin.tar.gz"
[[LCIO_Julia_Wrapper]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4bb8f579b9295f55569dcc6b581fb899bf0e235e"
libc = "glibc"
os = "linux"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "4928a2073f31d3445730ad6f896ff38455db1cebf9225d3d90906e843143c9cc"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.13.1+1/LCIO_Julia_Wrapper.v0.13.1.x86_64-linux-gnu-cxx03.tar.gz"
[[LCIO_Julia_Wrapper]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "700346a0db2cf2d2210351cee3f5d238d9aa1254"
libc = "glibc"
os = "linux"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "48b872ee947b38d1555fca4c4681f66e4aa46884d56edfc15027f8f7b9b4211a"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.13.1+1/LCIO_Julia_Wrapper.v0.13.1.x86_64-linux-gnu-cxx11.tar.gz"
