[[LCIO_Julia_Wrapper]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "81afd8396cabb927cf79adef984459aeac627b47"
os = "macos"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "9535c4246f7bc98f63a4732c897e94414678e8a52d28f5f85449a9c636a2d78e"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.8.1+0/LCIO_Julia_Wrapper.v0.8.1.x86_64-apple-darwin14-cxx11.tar.gz"
[[LCIO_Julia_Wrapper]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "641ff0dd8dba7c4dec8ef148eec49a443b3f1c88"
os = "macos"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "8ef8e761349f5d7ffef3e86d7cafd1addc905e7ff89b215c373f398dd6b64b2d"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.8.1+0/LCIO_Julia_Wrapper.v0.8.1.x86_64-apple-darwin14-cxx03.tar.gz"
[[LCIO_Julia_Wrapper]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "feb29035d68e8369055fd5c9ee057f4f633c8201"
libc = "glibc"
os = "linux"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "6bcede4c83760cd7316f2e6fa5ce7464cb86faccdeac4b300502316c52be9704"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.8.1+0/LCIO_Julia_Wrapper.v0.8.1.x86_64-linux-gnu-cxx11.tar.gz"
[[LCIO_Julia_Wrapper]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "26db3092933fc1d4e3440ed857f384564948e79f"
libc = "glibc"
os = "linux"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "645064cbd85dcb6b9e752fd6b091963ab91afaa068f86e91f2959a03efecdc38"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.8.1+0/LCIO_Julia_Wrapper.v0.8.1.x86_64-linux-gnu-cxx03.tar.gz"
