[[LCIO_Julia_Wrapper]]
arch = "x86_64"
git-tree-sha1 = "4102f044bc2a3db762907a9377f5cb3de8e1c846"
os = "macos"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "e7ead0567badee247e08f8b377590db2aee3952877de27b49a601410b4293b4c"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.13.1+0/LCIO_Julia_Wrapper.v0.13.1.x86_64-apple-darwin.tar.gz"
[[LCIO_Julia_Wrapper]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e4682050a41a60495ecdfdece930077c9c500ed1"
libc = "glibc"
os = "linux"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "5ddc7b0c8234a902dda0f6c79a02e4957907bf3a0e264d82bd2f4352b5a1e1ad"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.13.1+0/LCIO_Julia_Wrapper.v0.13.1.x86_64-linux-gnu-cxx03.tar.gz"
[[LCIO_Julia_Wrapper]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "189c9f5e2f60642f035a58a996df3d3145c2e82d"
libc = "glibc"
os = "linux"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "438270b1e850367d437f3b1d44991bf12652a757ad52f0f25599d74b06cd3f8e"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.13.1+0/LCIO_Julia_Wrapper.v0.13.1.x86_64-linux-gnu-cxx11.tar.gz"
