[[LCIO_Julia_Wrapper]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c7855dd6daa8b218910323b6a2a2c88194bbe440"
os = "macos"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "b5cd1c334299ce896a94fa51ead29521baaafde01cfa086c1604b8eeb9ba4875"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.11.0+0/LCIO_Julia_Wrapper.v0.11.0.x86_64-apple-darwin14-cxx11.tar.gz"
[[LCIO_Julia_Wrapper]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5499174f804c4610d98d89f5b2ce49031037f49b"
libc = "glibc"
os = "linux"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "703ecddb692842695d6ceff1fd10d83850308965703ab5aa81db41a41d2e66db"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.11.0+0/LCIO_Julia_Wrapper.v0.11.0.x86_64-linux-gnu-cxx11.tar.gz"
