[[LCIO_Julia_Wrapper]]
arch = "aarch64"
git-tree-sha1 = "27ca173a4738676c7a0982bb0607708164b5a529"
julia_version = "1.10.0"
os = "macos"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "7fb50606f1e2dea7ed7293fb2578b8ea46e0caf0c227398b5b183b8cd4569d77"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.13.4+0/LCIO_Julia_Wrapper.v0.13.4.aarch64-apple-darwin-julia_version+1.10.0.tar.gz"
[[LCIO_Julia_Wrapper]]
arch = "aarch64"
git-tree-sha1 = "686f8fbe8d3c26822b64df40f4fc7d2e3c33af2d"
julia_version = "1.11.1"
os = "macos"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "873cdf23100c6b34213c96f7b87e2f4bcb04a0347204c6dab6410472e0b5cc6e"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.13.4+0/LCIO_Julia_Wrapper.v0.13.4.aarch64-apple-darwin-julia_version+1.11.1.tar.gz"
[[LCIO_Julia_Wrapper]]
arch = "aarch64"
git-tree-sha1 = "7d0b9e5c777979b690553b6906a7e5fd65767e8b"
julia_version = "1.12.0"
os = "macos"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "cb47001cec121e4246ddd0b403e41a5ed02a2738530b2614d859804fd29b0735"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.13.4+0/LCIO_Julia_Wrapper.v0.13.4.aarch64-apple-darwin-julia_version+1.12.0.tar.gz"
[[LCIO_Julia_Wrapper]]
arch = "aarch64"
git-tree-sha1 = "02b0618322bf925822048b1562e3adae00a08de1"
julia_version = "1.13.0"
os = "macos"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "ea05918b89ce8c1eb36a7e79aeefeb766813d5ee736f638dbda6328b4b4609cf"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.13.4+0/LCIO_Julia_Wrapper.v0.13.4.aarch64-apple-darwin-julia_version+1.13.0.tar.gz"
[[LCIO_Julia_Wrapper]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ae564bfdec144676fe57e2585d4d68d81048c4be"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "23b3dbb5a205b0f18b66da05019bb433e3419c9e0fd29bf69a88751b8249ea86"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.13.4+0/LCIO_Julia_Wrapper.v0.13.4.aarch64-linux-gnu-cxx03-julia_version+1.10.0.tar.gz"
[[LCIO_Julia_Wrapper]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "14c8d6f09220f4ff3998865b2bf0d0bc178ef4d4"
julia_version = "1.11.1"
libc = "glibc"
os = "linux"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "78c497a995931cfd987e6a1819be275bbdbc67c13372b8904d96570e1c2923db"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.13.4+0/LCIO_Julia_Wrapper.v0.13.4.aarch64-linux-gnu-cxx03-julia_version+1.11.1.tar.gz"
[[LCIO_Julia_Wrapper]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ce00871cbdf480318f277b2103172fd8d0ae5cf3"
julia_version = "1.12.0"
libc = "glibc"
os = "linux"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "c2e046247aeeadf91c1ff69e33b761eceb487b7137e0d9154916b33c1178e880"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.13.4+0/LCIO_Julia_Wrapper.v0.13.4.aarch64-linux-gnu-cxx03-julia_version+1.12.0.tar.gz"
[[LCIO_Julia_Wrapper]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d6d0ceb367d212d2d9fbc357c0e2c7fc63aa42ad"
julia_version = "1.13.0"
libc = "glibc"
os = "linux"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "512ecb2d7e8a70ac9c6896263363c61cb83e66022f8fe9f11e3b278a0fed77fd"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.13.4+0/LCIO_Julia_Wrapper.v0.13.4.aarch64-linux-gnu-cxx03-julia_version+1.13.0.tar.gz"
[[LCIO_Julia_Wrapper]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "356915d05cd93ee609c3dc05d4444a586b930d6f"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "e1cb8c21761d313c4c51a98537e59e0f748d97365c4942970055bf973f4589d9"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.13.4+0/LCIO_Julia_Wrapper.v0.13.4.aarch64-linux-gnu-cxx11-julia_version+1.10.0.tar.gz"
[[LCIO_Julia_Wrapper]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "13d55f2112992c68643103f7aa883d3fe026d4f1"
julia_version = "1.11.1"
libc = "glibc"
os = "linux"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "d60becd7fa33bbbe285b0e35ec5bb634c9194ee6b43cddba4dec6f0ca2dbcb25"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.13.4+0/LCIO_Julia_Wrapper.v0.13.4.aarch64-linux-gnu-cxx11-julia_version+1.11.1.tar.gz"
[[LCIO_Julia_Wrapper]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "16fb99b4f9de87453867a8764d3f071d9f63be25"
julia_version = "1.12.0"
libc = "glibc"
os = "linux"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "4545d77528032704f9c19f599a956e15fbb9bd880f6bf2aa2dcf67716abf2b4c"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.13.4+0/LCIO_Julia_Wrapper.v0.13.4.aarch64-linux-gnu-cxx11-julia_version+1.12.0.tar.gz"
[[LCIO_Julia_Wrapper]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "02b2aa2327e5eb92523adf7f90c3ff3c99ebe3f3"
julia_version = "1.13.0"
libc = "glibc"
os = "linux"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "d1fdecbb3c4ef9b34d320d129b9e591b4d3bd8d85b097c1ab8ede747292f790f"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.13.4+0/LCIO_Julia_Wrapper.v0.13.4.aarch64-linux-gnu-cxx11-julia_version+1.13.0.tar.gz"
[[LCIO_Julia_Wrapper]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d5757b44eee7a56c42069c8dafbcc910b21a870c"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "5fb76510c9f571cef3c76c3d39c500ee828e6c3359f3f0d4a485e7d562880e64"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.13.4+0/LCIO_Julia_Wrapper.v0.13.4.powerpc64le-linux-gnu-cxx03-julia_version+1.10.0.tar.gz"
[[LCIO_Julia_Wrapper]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6c5ba02f2ada262018ad099627bd30ea8479510a"
julia_version = "1.11.1"
libc = "glibc"
os = "linux"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "5281c4514b1b25270f49c16c91075300fc56b6306b129cfb0e36bab307b7a4be"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.13.4+0/LCIO_Julia_Wrapper.v0.13.4.powerpc64le-linux-gnu-cxx03-julia_version+1.11.1.tar.gz"
[[LCIO_Julia_Wrapper]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f5983936656be56dae4778bec3dc58eca5c20823"
julia_version = "1.12.0"
libc = "glibc"
os = "linux"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "cb87b090dae1139ef201e21f79f92db9745810298c558af0e433cb90d39d6722"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.13.4+0/LCIO_Julia_Wrapper.v0.13.4.powerpc64le-linux-gnu-cxx03-julia_version+1.12.0.tar.gz"
[[LCIO_Julia_Wrapper]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ef6a0c75ae0e82f04e7da597c42d2bd5c55ca6c1"
julia_version = "1.13.0"
libc = "glibc"
os = "linux"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "739d4497c551e5eeba06644beda22e8523ed08e3d8daf25e68b460a1caa72074"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.13.4+0/LCIO_Julia_Wrapper.v0.13.4.powerpc64le-linux-gnu-cxx03-julia_version+1.13.0.tar.gz"
[[LCIO_Julia_Wrapper]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "24ce1fefb1c8932b89f4ee8af02a2e5822b9c6ff"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "fa7318229c687a43fff6a260391c88db3e5a1e9eaa75022dfac4287e55cb1403"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.13.4+0/LCIO_Julia_Wrapper.v0.13.4.powerpc64le-linux-gnu-cxx11-julia_version+1.10.0.tar.gz"
[[LCIO_Julia_Wrapper]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b50aef754bbf4f4bb05ebeacf4b26f4e69b7c4c3"
julia_version = "1.11.1"
libc = "glibc"
os = "linux"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "891548d783739a241f2f04412a929e88f82a268cfa05f26e43aece6854f34522"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.13.4+0/LCIO_Julia_Wrapper.v0.13.4.powerpc64le-linux-gnu-cxx11-julia_version+1.11.1.tar.gz"
[[LCIO_Julia_Wrapper]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a85e7a25d9f34d98e40088feb9550b5280e5b14d"
julia_version = "1.12.0"
libc = "glibc"
os = "linux"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "44b264aa5c56afd2b388142369546f568fd6cd9eff0e1defafe7a0e21c3a5e7e"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.13.4+0/LCIO_Julia_Wrapper.v0.13.4.powerpc64le-linux-gnu-cxx11-julia_version+1.12.0.tar.gz"
[[LCIO_Julia_Wrapper]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e705c64f0b4e6ec3f2467ea41b8cd13df042004a"
julia_version = "1.13.0"
libc = "glibc"
os = "linux"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "414bc4b7201d61e50f49e5d0f9247c5259e314e68d8ba1b18f3e87670549d981"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.13.4+0/LCIO_Julia_Wrapper.v0.13.4.powerpc64le-linux-gnu-cxx11-julia_version+1.13.0.tar.gz"
[[LCIO_Julia_Wrapper]]
arch = "riscv64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d2ed67c8c4f89f9556c86fff64fc2ab0d94ee697"
julia_version = "1.13.0"
libc = "glibc"
os = "linux"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "3469644c171e64e3fed59a8964c2fb94b22bc7d7021c9779482423d02e082153"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.13.4+0/LCIO_Julia_Wrapper.v0.13.4.riscv64-linux-gnu-cxx03-julia_version+1.13.0.tar.gz"
[[LCIO_Julia_Wrapper]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f1d988f9ccf750df38e6f7370d647d8683110abb"
julia_version = "1.13.0"
libc = "glibc"
os = "linux"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "c017e3e88fcc3d67f06ecfa5f16a9fb530ab195aa5d5429b560d3aee89dc6c22"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.13.4+0/LCIO_Julia_Wrapper.v0.13.4.riscv64-linux-gnu-cxx11-julia_version+1.13.0.tar.gz"
[[LCIO_Julia_Wrapper]]
arch = "x86_64"
git-tree-sha1 = "e2cfb46bfd2aade68e83ede59adb3c800e563eac"
julia_version = "1.10.0"
os = "macos"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "75d86de5dc4801749a4638eb29d17aee91586c42c7fec9b31b3c7a33f1465a0e"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.13.4+0/LCIO_Julia_Wrapper.v0.13.4.x86_64-apple-darwin-julia_version+1.10.0.tar.gz"
[[LCIO_Julia_Wrapper]]
arch = "x86_64"
git-tree-sha1 = "369b85bfa203d320d76abf6756f751e87b30f113"
julia_version = "1.11.1"
os = "macos"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "8af1878d0b73c4ca2da8111223a67845152ec4e2db00c8eddcbd6cdc9635ecb7"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.13.4+0/LCIO_Julia_Wrapper.v0.13.4.x86_64-apple-darwin-julia_version+1.11.1.tar.gz"
[[LCIO_Julia_Wrapper]]
arch = "x86_64"
git-tree-sha1 = "5ce10d33b6c78e7dc969220959fb9e58d48afbdc"
julia_version = "1.12.0"
os = "macos"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "ab8285c9c6029eb29a288eca17799f01f89432b55f1a464f122a7f4f69c076df"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.13.4+0/LCIO_Julia_Wrapper.v0.13.4.x86_64-apple-darwin-julia_version+1.12.0.tar.gz"
[[LCIO_Julia_Wrapper]]
arch = "x86_64"
git-tree-sha1 = "e0dc07bdf9cd1fd0c3150474b3d8667f5ee7d3e0"
julia_version = "1.13.0"
os = "macos"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "9f6ee9151a25ae3dab67f38263eef02f15fcfdba530e748aeea00ed6dad5b7c3"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.13.4+0/LCIO_Julia_Wrapper.v0.13.4.x86_64-apple-darwin-julia_version+1.13.0.tar.gz"
[[LCIO_Julia_Wrapper]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3984f0655bcff4f67f400f93dd58246eb38f5310"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "5ce5235f5252a3ce5551835cb8259b435f321f460a96669bb6785e506d5e0310"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.13.4+0/LCIO_Julia_Wrapper.v0.13.4.x86_64-linux-gnu-cxx03-julia_version+1.10.0.tar.gz"
[[LCIO_Julia_Wrapper]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "10b164a2cf408b587fa53e89a303f32288e797c0"
julia_version = "1.11.1"
libc = "glibc"
os = "linux"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "34a1b746d4e02cbc16816cf6dfe9b68efdb43c200717fdca88955cdd0ffbafa7"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.13.4+0/LCIO_Julia_Wrapper.v0.13.4.x86_64-linux-gnu-cxx03-julia_version+1.11.1.tar.gz"
[[LCIO_Julia_Wrapper]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0615ce98df97110d4e645217ab698d3e9f829023"
julia_version = "1.12.0"
libc = "glibc"
os = "linux"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "f011cd6f8f3d48fb3a58c60627f68caa837104dd2dc0d69246eb7003cde5646f"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.13.4+0/LCIO_Julia_Wrapper.v0.13.4.x86_64-linux-gnu-cxx03-julia_version+1.12.0.tar.gz"
[[LCIO_Julia_Wrapper]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bfb92c2b7dabe0d713579f214af3cde3c31846dd"
julia_version = "1.13.0"
libc = "glibc"
os = "linux"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "b61f1c24af32af6d0d7600a1e146aa68ebc1fab03e2d299f0211aa500ced1b1c"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.13.4+0/LCIO_Julia_Wrapper.v0.13.4.x86_64-linux-gnu-cxx03-julia_version+1.13.0.tar.gz"
[[LCIO_Julia_Wrapper]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8cf9a7d968701dc94130110b776f736437ccb772"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "491133707821eec179be0d483641d1413ffcb188ce23fa721bd8853c544ac5aa"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.13.4+0/LCIO_Julia_Wrapper.v0.13.4.x86_64-linux-gnu-cxx11-julia_version+1.10.0.tar.gz"
[[LCIO_Julia_Wrapper]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "23024f1ba077ca16e140eca4aba520d47a40fc89"
julia_version = "1.11.1"
libc = "glibc"
os = "linux"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "3f18d25797ce59dc5c7f1100a81554d33b54e66fc341012dca19393e97030941"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.13.4+0/LCIO_Julia_Wrapper.v0.13.4.x86_64-linux-gnu-cxx11-julia_version+1.11.1.tar.gz"
[[LCIO_Julia_Wrapper]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "10cc0943d63e0b763d8a1498601a09f356198284"
julia_version = "1.12.0"
libc = "glibc"
os = "linux"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "586fc977e7ddef8e23111eae8d06c3088642ce53f1d48d81040b603e74bbd802"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.13.4+0/LCIO_Julia_Wrapper.v0.13.4.x86_64-linux-gnu-cxx11-julia_version+1.12.0.tar.gz"
[[LCIO_Julia_Wrapper]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1c52e7daa586734ddde653dba7f499c7bb6488fd"
julia_version = "1.13.0"
libc = "glibc"
os = "linux"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "cd60624d26fdecc6680abc28c565de54073129476d970115a76c2819427f7bb0"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.13.4+0/LCIO_Julia_Wrapper.v0.13.4.x86_64-linux-gnu-cxx11-julia_version+1.13.0.tar.gz"
