[[LCIO_Julia_Wrapper]]
arch = "aarch64"
git-tree-sha1 = "2690a921eaeea720e44cd891626f97a9f42fe722"
julia_version = "1.10.0"
os = "macos"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "c5e5b5ddd7f7b45cf8bd31099507cfe300807e2dcd2b8406e2fe81eae6efa4e0"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.13.3+0/LCIO_Julia_Wrapper.v0.13.3.aarch64-apple-darwin-julia_version+1.10.0.tar.gz"
[[LCIO_Julia_Wrapper]]
arch = "aarch64"
git-tree-sha1 = "07855c32e0993e71c099ddce156b78e8d7e4a082"
julia_version = "1.7.0"
os = "macos"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "072205f9fb83907252542042e11cff6500063aa07bceb921a4c0870c4be0071e"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.13.3+0/LCIO_Julia_Wrapper.v0.13.3.aarch64-apple-darwin-julia_version+1.7.0.tar.gz"
[[LCIO_Julia_Wrapper]]
arch = "aarch64"
git-tree-sha1 = "c85346a7d070c7560a84cb5cea15cd6c998b6d81"
julia_version = "1.8.0"
os = "macos"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "0d03297c993cdcb3ba241fcf8b44beebbbccdb53125e224c07ba18007c13c766"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.13.3+0/LCIO_Julia_Wrapper.v0.13.3.aarch64-apple-darwin-julia_version+1.8.0.tar.gz"
[[LCIO_Julia_Wrapper]]
arch = "aarch64"
git-tree-sha1 = "03f37b7871793562451bb379e8b6c5f041ae3860"
julia_version = "1.9.0"
os = "macos"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "4d7907ee524acd053d25f9150dfce2ca4151b1976e6ee2ce7f3509298d01b91d"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.13.3+0/LCIO_Julia_Wrapper.v0.13.3.aarch64-apple-darwin-julia_version+1.9.0.tar.gz"
[[LCIO_Julia_Wrapper]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1b6ed362ba0679a8c8cdecf19a9e8bdaed600d6a"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "f6e24e7a100654755396291e4c35799d4f3ac5cdc82ef3fd6aa42fa9577f7a14"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.13.3+0/LCIO_Julia_Wrapper.v0.13.3.aarch64-linux-gnu-cxx03-julia_version+1.10.0.tar.gz"
[[LCIO_Julia_Wrapper]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "115564fe589154abe7499633af0e43bd68586db5"
julia_version = "1.6.3"
libc = "glibc"
os = "linux"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "109eb5ba3b8d3aa8d2f911e2603e2df7a476eccb31c5a037ea69ce3892328d89"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.13.3+0/LCIO_Julia_Wrapper.v0.13.3.aarch64-linux-gnu-cxx03-julia_version+1.6.3.tar.gz"
[[LCIO_Julia_Wrapper]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dbf9f60bd7c44ef16dec522614a2b405b34f870c"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "2a990cd12ff3ab14c5a1a7e309903ca070eac4c5f22057148dc7d8fb3105c6e2"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.13.3+0/LCIO_Julia_Wrapper.v0.13.3.aarch64-linux-gnu-cxx03-julia_version+1.7.0.tar.gz"
[[LCIO_Julia_Wrapper]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8d212bd7e8f651206e6a389523b33d0ea5bd485d"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "a1c8fe6536083a91a92b5d6abd6d17bd56e7f1dea15be74f41563da8ae2da800"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.13.3+0/LCIO_Julia_Wrapper.v0.13.3.aarch64-linux-gnu-cxx03-julia_version+1.8.0.tar.gz"
[[LCIO_Julia_Wrapper]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "518d88766b0e5dfeedcd6fbd5bce76c2706a91dd"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "c6c24f974e035751648ad067781430df65b7d52fa6337b96d50815434cb0ef53"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.13.3+0/LCIO_Julia_Wrapper.v0.13.3.aarch64-linux-gnu-cxx03-julia_version+1.9.0.tar.gz"
[[LCIO_Julia_Wrapper]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "793fc393294b1a89ad063d4d94149b9b4f2c3b28"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "6a5fec1e73cca3759be789b5932e7c09c416517d1d06e0509e416663dad92f20"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.13.3+0/LCIO_Julia_Wrapper.v0.13.3.aarch64-linux-gnu-cxx11-julia_version+1.10.0.tar.gz"
[[LCIO_Julia_Wrapper]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "afee8df08d8f470d77470cc6c8517a2521b0846f"
julia_version = "1.6.3"
libc = "glibc"
os = "linux"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "67f039261beed7c879c671d7513a41ed67f7701b647f71732ae10f83457ff56d"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.13.3+0/LCIO_Julia_Wrapper.v0.13.3.aarch64-linux-gnu-cxx11-julia_version+1.6.3.tar.gz"
[[LCIO_Julia_Wrapper]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0438d68859b19b2c119d40affb9ae20796a80b04"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "18f6546ef0bce9556eaa5b13badc2d0bd56ff15910c0887da1c5c6e43bdeb867"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.13.3+0/LCIO_Julia_Wrapper.v0.13.3.aarch64-linux-gnu-cxx11-julia_version+1.7.0.tar.gz"
[[LCIO_Julia_Wrapper]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "06cf8829cae8af3c2e7dca6ad958cd3aeefbfaa2"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "18a89522e05d913221083b3e6b0bbf7967d6a67e8ac642abe2157b07bcb43c97"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.13.3+0/LCIO_Julia_Wrapper.v0.13.3.aarch64-linux-gnu-cxx11-julia_version+1.8.0.tar.gz"
[[LCIO_Julia_Wrapper]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "14901260e8b4624631e72d981c9b7ce5f47e94d9"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "13758d57b5ed487adce0508027091e93342d8147cd4affec7b399610a2998edf"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.13.3+0/LCIO_Julia_Wrapper.v0.13.3.aarch64-linux-gnu-cxx11-julia_version+1.9.0.tar.gz"
[[LCIO_Julia_Wrapper]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "76879e4080c74242599dcb9fc05b569177ed7d1e"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "70eaf2ff1f09d1278b38860729fa4081c33c7dde34ca0db5f1bdb704ef1dd747"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.13.3+0/LCIO_Julia_Wrapper.v0.13.3.powerpc64le-linux-gnu-cxx03-julia_version+1.10.0.tar.gz"
[[LCIO_Julia_Wrapper]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7f39f44c55171f6b7ee65b887dea0b3a21a00608"
julia_version = "1.6.3"
libc = "glibc"
os = "linux"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "9648e8811021514e3b6c2e45d1064d3b808bd012b9ba06d89a3e93f686d786ce"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.13.3+0/LCIO_Julia_Wrapper.v0.13.3.powerpc64le-linux-gnu-cxx03-julia_version+1.6.3.tar.gz"
[[LCIO_Julia_Wrapper]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "eb6d11ef6b80c1e7570e9ea9a4e75688b99f931b"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "d2e94176a0596016c48643ab36686f43870e9316156a0f09830149e417a1106c"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.13.3+0/LCIO_Julia_Wrapper.v0.13.3.powerpc64le-linux-gnu-cxx03-julia_version+1.7.0.tar.gz"
[[LCIO_Julia_Wrapper]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "03619224365e2cc6c2b66b7c17c33fcb492a648c"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "21e79edfdfc7e764e11a2c7a129521daad40a9c1b386034b59bba53a7cd2b37a"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.13.3+0/LCIO_Julia_Wrapper.v0.13.3.powerpc64le-linux-gnu-cxx03-julia_version+1.8.0.tar.gz"
[[LCIO_Julia_Wrapper]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2a3bac730f7e644ccc83dca3e4bef6afeb8c1c2c"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "a7f1026109bc940450f3a51c0a4f3498a223ca6a9bfcbbbc1152c44f58db43c9"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.13.3+0/LCIO_Julia_Wrapper.v0.13.3.powerpc64le-linux-gnu-cxx03-julia_version+1.9.0.tar.gz"
[[LCIO_Julia_Wrapper]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "347503646f18102fb4dece3777cd9b46565eb49f"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "ab9dae68a6283e48c5591cad6335166258b70c42171422c28a560734c50e0bd1"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.13.3+0/LCIO_Julia_Wrapper.v0.13.3.powerpc64le-linux-gnu-cxx11-julia_version+1.10.0.tar.gz"
[[LCIO_Julia_Wrapper]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "88c3a155f54e7d7a081f00edc89048f2c3cf9ef7"
julia_version = "1.6.3"
libc = "glibc"
os = "linux"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "146f35ab4ea22e73e5263e394b345112dc25cfda3618e9668238b52609cda245"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.13.3+0/LCIO_Julia_Wrapper.v0.13.3.powerpc64le-linux-gnu-cxx11-julia_version+1.6.3.tar.gz"
[[LCIO_Julia_Wrapper]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1f4e057fb869c0605a3dab05d089f19ed06d4a78"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "3a114bed403ad5ea85daf7852da42e2c52e2e6483ae9e6cde9e9948c3a320daf"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.13.3+0/LCIO_Julia_Wrapper.v0.13.3.powerpc64le-linux-gnu-cxx11-julia_version+1.7.0.tar.gz"
[[LCIO_Julia_Wrapper]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "522f44d937d2394f41ae8c058e3a42dcf474e773"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "2b232e378c2287f79286c8d2776fff11ad55257edef2e8bd814fda6b2881e326"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.13.3+0/LCIO_Julia_Wrapper.v0.13.3.powerpc64le-linux-gnu-cxx11-julia_version+1.8.0.tar.gz"
[[LCIO_Julia_Wrapper]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f412cce4ba99c8fc9c0ba003f187e3f5434106f2"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "ccbfa2f505bb8036ec10edfac3695442e4f74f7147001e587bde209b076d8cdc"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.13.3+0/LCIO_Julia_Wrapper.v0.13.3.powerpc64le-linux-gnu-cxx11-julia_version+1.9.0.tar.gz"
[[LCIO_Julia_Wrapper]]
arch = "x86_64"
git-tree-sha1 = "d71f1c128318e2849337ee231ca717dd1a49f56c"
julia_version = "1.10.0"
os = "macos"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "564b54ea65fe248bcdf8fb304990df7c9098ef311ebf656d3d15d76eb196b656"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.13.3+0/LCIO_Julia_Wrapper.v0.13.3.x86_64-apple-darwin-julia_version+1.10.0.tar.gz"
[[LCIO_Julia_Wrapper]]
arch = "x86_64"
git-tree-sha1 = "2daf792886109bca22117d6a701549934f48ca7a"
julia_version = "1.6.3"
os = "macos"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "2c10ad21a2bc067219fa43d04b73c6cee91688bdc39ff19f6a56922af69fe114"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.13.3+0/LCIO_Julia_Wrapper.v0.13.3.x86_64-apple-darwin-julia_version+1.6.3.tar.gz"
[[LCIO_Julia_Wrapper]]
arch = "x86_64"
git-tree-sha1 = "70b84412b38b35cc2a2fb6dd1cfca253a785d6e4"
julia_version = "1.7.0"
os = "macos"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "751eb44f7e4e27bab72e171c7ef477d63ec249bb591417289319a934e59f43b5"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.13.3+0/LCIO_Julia_Wrapper.v0.13.3.x86_64-apple-darwin-julia_version+1.7.0.tar.gz"
[[LCIO_Julia_Wrapper]]
arch = "x86_64"
git-tree-sha1 = "9a72c5bf4515642badf237193fb54e579cd9efba"
julia_version = "1.8.0"
os = "macos"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "206952c74ff878c39de048d0b6bf8d89bf1c7b86177a517097b7cbb29115839b"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.13.3+0/LCIO_Julia_Wrapper.v0.13.3.x86_64-apple-darwin-julia_version+1.8.0.tar.gz"
[[LCIO_Julia_Wrapper]]
arch = "x86_64"
git-tree-sha1 = "728649b0caf9e2764dca868ce6ed0e845e13619b"
julia_version = "1.9.0"
os = "macos"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "46367530178315e4a80cfecd004d22c68e88b4a2261ea83ede00317129cf7fdb"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.13.3+0/LCIO_Julia_Wrapper.v0.13.3.x86_64-apple-darwin-julia_version+1.9.0.tar.gz"
[[LCIO_Julia_Wrapper]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7be69339c294cb1ac33f94756d999179fceaddc4"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "e01bf0d22889bca0a012586cd01bed7aec5017546ac34c71cd6d91c3b96a35df"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.13.3+0/LCIO_Julia_Wrapper.v0.13.3.x86_64-linux-gnu-cxx03-julia_version+1.10.0.tar.gz"
[[LCIO_Julia_Wrapper]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "97d1c63b4683f4a8e3d770665ffddafe0934200e"
julia_version = "1.6.3"
libc = "glibc"
os = "linux"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "18617b67cb22b0471559291b0d8190172bbddd12910891c6d8cbfe655609f3b9"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.13.3+0/LCIO_Julia_Wrapper.v0.13.3.x86_64-linux-gnu-cxx03-julia_version+1.6.3.tar.gz"
[[LCIO_Julia_Wrapper]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "85b6b8b2d38c8d82acbb60dd3874468cf0bc910a"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "b54fee74ef4a08d53c5b77df8e90092060217fc2be3d74b27a46e43c644b3ff7"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.13.3+0/LCIO_Julia_Wrapper.v0.13.3.x86_64-linux-gnu-cxx03-julia_version+1.7.0.tar.gz"
[[LCIO_Julia_Wrapper]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2e5cbb9e7ef3e5ffda5d70180820bb6f789c65f4"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "d68e8d28eb22b9df6a195ded9e2ff8e2a1b27224e35d7989b54c0e0389b3e373"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.13.3+0/LCIO_Julia_Wrapper.v0.13.3.x86_64-linux-gnu-cxx03-julia_version+1.8.0.tar.gz"
[[LCIO_Julia_Wrapper]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b6d794b61eafa54c3213c3259ff96d2fb76d6340"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "be4dd0c9dad8a82d4f8d7085da0a1bfffe118c2b041f874c3c88477edaaed71b"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.13.3+0/LCIO_Julia_Wrapper.v0.13.3.x86_64-linux-gnu-cxx03-julia_version+1.9.0.tar.gz"
[[LCIO_Julia_Wrapper]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4d2ca4d6a01fe018562f377da521fe005027577d"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "622d09a068be3cb3c900ac96b0ce6fdaed9097228743c4183183acbe451aa24a"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.13.3+0/LCIO_Julia_Wrapper.v0.13.3.x86_64-linux-gnu-cxx11-julia_version+1.10.0.tar.gz"
[[LCIO_Julia_Wrapper]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4987d9b5fc1d1cb8dd4c481218004c94d4cf623e"
julia_version = "1.6.3"
libc = "glibc"
os = "linux"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "0edaab905567af69ce96aeaf1bc9bc275cada45903f837509c872269c66195fc"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.13.3+0/LCIO_Julia_Wrapper.v0.13.3.x86_64-linux-gnu-cxx11-julia_version+1.6.3.tar.gz"
[[LCIO_Julia_Wrapper]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6bb69ac4b5c23c43dafa6da08551b0983ae87bbf"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "5d505882a5495b0461470670d835c8a3bb63440aae7c1b8a6979170060667c3e"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.13.3+0/LCIO_Julia_Wrapper.v0.13.3.x86_64-linux-gnu-cxx11-julia_version+1.7.0.tar.gz"
[[LCIO_Julia_Wrapper]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ec5a0bce464d91e831a765df13be4b641f74e57f"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "7683e11c1d69cc962852b8cc49fb697acd808bc28869f8cefc8c60e47ed91b92"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.13.3+0/LCIO_Julia_Wrapper.v0.13.3.x86_64-linux-gnu-cxx11-julia_version+1.8.0.tar.gz"
[[LCIO_Julia_Wrapper]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7d3aab4262926a09d828019625b51224393702e0"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "0674ef9a288780d89d1fb1ca74eb1d0969aa701f7160a07261c610c376bb1116"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.13.3+0/LCIO_Julia_Wrapper.v0.13.3.x86_64-linux-gnu-cxx11-julia_version+1.9.0.tar.gz"
