[[LCIO_Julia_Wrapper]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "919c9770ee5f6179282c4bb3fe1dd0a8f6ea616b"
os = "macos"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "8458642b7375b23f5e8b1af244ee42a620875a2cd2afe5dcad90df7bdb926bf0"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.9.0+0/LCIO_Julia_Wrapper.v0.9.0.x86_64-apple-darwin14-cxx11.tar.gz"
[[LCIO_Julia_Wrapper]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ef836fdeac917e7a7dcc81500cecd5ee3c645f2a"
libc = "glibc"
os = "linux"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "cb743ba22f1a7a0156b8ac10e456e62a365e7bba578f32a75857b4be4c98ce32"
    url = "https://github.com/JuliaBinaryWrappers/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.9.0+0/LCIO_Julia_Wrapper.v0.9.0.x86_64-linux-gnu-cxx11.tar.gz"
